apiVersion: apps/v1
kind: Deployment
metadata:
  name: poll-system-deployment
  namespace: poll-system
  labels:
    app: poll-system
spec:
  replicas: 3
  selector:
    matchLabels:
      app: poll-system
  template:
    metadata:
      labels:
        app: poll-system
    spec:
      containers:
      - name: poll-system
        image: poll-system:latest
        imagePullPolicy: IfNotPresent
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: poll-system-secrets
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poll-system-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_PORT
        - name: ALLOWED_HOSTS
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: ALLOWED_HOSTS
        ports:
        - containerPort: 8000
          name: http
        livenessProbe:
          httpGet:
            path: /api/v1/statistics/
            port: 8000
          initialDelaySeconds: 30
          timeoutSeconds: 10
          periodSeconds: 30
        readinessProbe:
          httpGet:
            path: /api/v1/statistics/
            port: 8000
          initialDelaySeconds: 10
          timeoutSeconds: 5
          periodSeconds: 10
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
      initContainers:
      - name: migrate
        image: poll-system:latest
        command: ['python', 'manage.py', 'migrate']
        env:
        - name: DEBUG
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DEBUG
        - name: SECRET_KEY
          valueFrom:
            secretKeyRef:
              name: poll-system-secrets
              key: SECRET_KEY
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_NAME
        - name: DB_USER
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_USER
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: poll-system-secrets
              key: DB_PASSWORD
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_HOST
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: poll-system-config
              key: DB_PORT
---
apiVersion: v1
kind: Service
metadata:
  name: poll-system-service
  namespace: poll-system
spec:
  selector:
    app: poll-system
  ports:
  - port: 80
    targetPort: 8000
    protocol: TCP
  type: LoadBalancer