apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poll-system-ingress
  namespace: poll-system
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
spec:
  rules:
  - host: poll-system.local
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: poll-system-service
            port:
              number: 80
---
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: poll-system-hpa
  namespace: poll-system
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: poll-system-deployment
  minReplicas: 2
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:
        type: Utilization
        averageUtilization: 70
  - type: Resource
    resource:
      name: memory
      target:
        type: Utilization
        averageUtilization: 80