# Generated by Django 5.2.6 on 2025-09-20 13:54

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(help_text='Poll title must be at least 5 characters', max_length=200, validators=[django.core.validators.MinLengthValidator(5)])),
                ('description', models.TextField(blank=True, help_text='Optional detailed description of the poll', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when poll was created')),
                ('expires_at', models.DateTimeField(blank=True, db_index=True, help_text='Optional expiration date for the poll', null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True, help_text='Whether the poll is currently accepting votes')),
                ('created_by', models.ForeignKey(blank=True, help_text='User who created the poll', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='polls', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Option',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(help_text='Option text must be at least 2 characters', max_length=200, validators=[django.core.validators.MinLengthValidator(2)])),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order of the option')),
                ('poll', models.ForeignKey(help_text='Poll this option belongs to', on_delete=django.db.models.deletion.CASCADE, related_name='options', to='polls.poll')),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='Vote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('voter_ip', models.GenericIPAddressField(help_text='IP address of the voter for duplicate prevention')),
                ('voter_session', models.CharField(help_text='Session key for duplicate prevention', max_length=40)),
                ('voted_at', models.DateTimeField(auto_now_add=True, db_index=True, help_text='Timestamp when vote was cast')),
                ('option', models.ForeignKey(help_text='Option that was voted for', on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='polls.option')),
            ],
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['is_active', 'created_at'], name='polls_poll_is_acti_b4c47c_idx'),
        ),
        migrations.AddIndex(
            model_name='poll',
            index=models.Index(fields=['expires_at', 'is_active'], name='polls_poll_expires_cf2b47_idx'),
        ),
        migrations.AddIndex(
            model_name='option',
            index=models.Index(fields=['poll', 'order'], name='polls_optio_poll_id_34e3f7_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='option',
            unique_together={('poll', 'text')},
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['option', 'voted_at'], name='polls_vote_option__d64661_idx'),
        ),
        migrations.AddIndex(
            model_name='vote',
            index=models.Index(fields=['voter_ip', 'voter_session'], name='polls_vote_voter_i_823a9e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='vote',
            unique_together={('option', 'voter_ip', 'voter_session')},
        ),
    ]
